on:
  push:
    branches:
    - master

name: push image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: extract tag
      id: vars
      run: echo ::set-output name=nginx_version::$(head -n2 Dockerfile | tail -n1 | cut -d ' ' -f 2 | cut -d ':' -f 2)
    - run: echo "Pushing version ${{ steps.vars.outputs.nginx_version }}"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: "ironpeakservices/iron-nginx:${{ steps.vars.outputs.nginx_version }}"
        username: hazcod
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: rm /github/home/.docker/config.json


