on:
  push:
    branches:
    - master

name: push image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: extract tag
      id: vars
      run: echo ::set-output name=nginx_version::$(grep '^FROM nginx' Dockerfile  | cut -d ' ' -f 2 | cut -d ':' -f 2)
    - run: echo "Pushing version ${{ steps.vars.outputs.nginx_version }}"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        registry: docker.pkg.github.com
        name: "ironpeakservices/iron-nginx/iron-nginx:${{ steps.vars.outputs.nginx_version }}"
        username: hazcod
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
          tag_name: ${{ steps.vars.outputs.nginx_version }}
          release_name: iron-nginx
          draft: false
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


