on:
  push:
    branches:
    - master

name: push image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: extract tag
      run: echo ::set-env name=NGINX_VERSION::$(head -n2 Dockerfile | tail -n1 | cut -d ' ' -f 2 | cut -d ':' -f 2)
    - run: echo "Pushing version $NGINX_VERSION"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: "ironpeakservices/iron-nginx:${NGINX_VERSION}"
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: rm /github/home/.docker/config.json


